# Generated by Django 2.1.8 on 2020-03-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('number', models.CharField(max_length=32, verbose_name='学号')),
                ('is_upload', models.CharField(max_length=32, null=True, verbose_name='是否上传')),
                ('upload_time', models.CharField(max_length=64, verbose_name='上传时间')),
            ],
        ),
    ]
